### ISSUE TITLE
Unable to download this game, just immediately gives an error

### ISSUE THREAD

**Issue by ManMan3616** [Kassy2048/rags2html#1]
https://mega.nz/file/p2YEEILa#lOQ9AAs6eiUcFIew9mmvnRlBS6iffnjBbxHVqL9eDU8

**Comment by Kassy2048** [comment]
What is the error message? If you use the online version, which browser?

The file is converted successfully for me both with Firefox and Chrome, and with the Python script. It fails on my mobile, but that's expected (the file is too big). I've posted the converted ZIP file on f95zone btw.
