### ISSUE TITLE
Two games don't seems to be working the right way

### ISSUE THREAD

**Issue by nanabanana321** [Kassy2048/rags2html#3]
https://www.mediafire.com/?9trnrr48og2fj6b
1st game

2nd game
https://www.mediafire.com/?j2hgnonm2puxbfh

The buttons don't seems to be working maybe it's something built in the games?

Anyway great work!

**Comment by Kassy2048** [comment]
Thanks for the kind words😊

I see where the problem is in the code, but I'm a bit busy rn to fix it. I'll try to do that later this week.

**Comment by Kassy2048** [comment]
Convert the games again and that should be fixed.
