### ISSUE TITLE
this game conversion failed

### ISSUE THREAD

**Issue by hexiediyi** [Kassy2048/rags2html#4]
[/rags/Hornets Nest 0v293.rag]
Decrypting file...
Loading file...
Extracting medias...
Converting old format...
Converting game data to JS...
Traceback (most recent call last):
  File "/home/pyodide/rags2html.py", line 1946, in main
    await asyncio.create_task(process_file(fpath, keys, args, progress=progress))
  File "/home/pyodide/rags2html.py", line 1887, in process_file
    game_js = create_game_js(game, images=images, variables=variables, statusbars=statusbars,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pyodide/rags2html.py", line 374, in create_game_js
    GameFont = TextFont.convert(game.get('GameFont', '(none)'), 'Microsoft Sans Serif, 8.25pt')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pyodide/compat.py", line 231, in convert
    for k, v in TextFont.STYLES:
        ^^^^
TypeError: cannot unpack non-iterable int object
ERROR in /rags/Hornets Nest 0v293.rag

download link:http://www.mediafire.com/?serhl57wp50fb5l
all filed on edge and chrome
game is no password protection

**Comment by Kassy2048** [comment]
Thanks for reporting the problem. I've fixed it in 9ba930e4afe9a73d792319e7aad62a69125af0c1.

There were another problem in Regalia with this game that I've fixed in https://github.com/Kassy2048/regalia/commit/0e417a1c94038ae600a0ecc3f55154fa706e4663

**Comment by hexiediyi** [comment]
thanks a lot
