### ISSUE TITLE
Error on attempted move between rooms

### ISSUE THREAD

**Issue by twilight-flower** [Kassy2048/rags2html#5]
I converted a game, ran it, attempted to move from one room to another for the first time, and immediately ran into an error:

```
Rags can not process the condition check correctly.  If you are the game author, please correct the error in this conditon:Character in dest room? check:CT_Character_In_Room - [char.name] - [tp: GetCount : Results] - 
```

(This error doesn't come up when I run the game in RAGS Player 2.4.16 on Windows.)

Game download link: https://www.mediafire.com/?ctzxbijtmlfm5r3

**Comment by Kassy2048** [comment]
Thanks for reporting the issue.

This should be fixed now, convert the game again and check.

**Comment by twilight-flower** [comment]
It does indeed seem to be fixed. Thanks!
